FROM python:3.11.11-bookworm as base
WORKDIR /workspace

RUN apt-get update && apt-get install -y \
    git \
    tree \
    stow \
    libglew-dev \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /out /in

COPY ./requirements.txt requirements.txt
RUN pip install --upgrade pip && pip install -r requirements.txt

RUN useradd -ms /bin/bash pcd && mkdir -p /home/pcd/.config && chown -R pcd:pcd /home/pcd
USER pcd


CMD ["/bin/bash"]
